export const APP_CONSTANTS = {
    STORAGE_CAPACITY_UPLOAD: 1,
    STORAGE_CAPACITY_SOURCE: 1,
    STORAGE_CAPACITY_SHARE: 1,

    COLOR_ITEM_SIDEBAR_PARENT_ACTIVE: '#1a1a1a',
    COLOR_ITEM_SIDEBAR: '#8c8c8c',
    COLOR_ITEM_SIDEBAR_CHILD_ACTIVE: '#0a53be',

}
